### PR TITLE
Update feliz

### PR DESCRIPTION
**Pull request by martinbryant**
As this package uses v1.x of Feliz and Fable React it has conflicts when trying to use in a project that uses Feliz v2.x. This PR will update all things Feliz, React and Fable

### CODE REVIEW

**Review by mattgallagher92 — APPROVED** [review]
All good! Perhaps it'd be worth including a changelog (CHANGELOG.md?) to record that there is a breaking change, in case package users come wondering why the latest version of the package doesn't work for them?

I'm okay with that going into a separate PR (or even into an issue that you don't raise a PR for) if you're keen to get this out soon to unblock you.

**Comment by martinbryant** [comment]
> All good! Perhaps it'd be worth including a changelog (CHANGELOG.md?) to record that there is a breaking change, in case package users come wondering why the latest version of the package doesn't work for them?
> 
> I'm okay with that going into a separate PR (or even into an issue that you don't raise a PR for) if you're keen to get this out soon to unblock you.

Completely agree and so I think we should go with a v1 release as it is a breaking change.

I have gone with a version compatibility chart on the readme and would be great to get your thoughts

**Review by mattgallagher92 — APPROVED** [review]
Perfect!

**Comment by martinbryant** [comment]
#16

**Pull request merged**
